#
# Cluster and Cloud Computing - Team 20
# 
# Authors: 
#
#  Cenxi Si, Student ID: 1052447
#  Yipei Liu, Student ID: 1067990
#  Jingdan Zhang, Student ID: 1054101
#  Chengyan Dai, Student ID: 1054219
#  Ruimin Sun, Student ID: 1052182
#

---
volumns:
  -- mountpoint: /data
  -- mountpoint: /var/lib/docker

master: 172.26.131.170
user: admin
password: '170645'
cookie: '5d9e893d8a694f7e78179991f8f610d3'
uuid: '078489b204f054d85293ec8d37f88b69'
couchdb_version: 3.2.0