#
# Cluster and Cloud Computing - Team 20
# 
# Authors: 
#
#  Cenxi Si, Student ID: 1052447, China
#  Yipei Liu, Student ID: 1067990, China
#  Jingdan Zhang, Student ID: 1054101, China
#  Chengyan Dai, Student ID: 1054219, Melbourne
#  Ruimin Sun, Student ID: 1052182, China
#

---
volumes:
  - mountpoint: /var/lib/docker
  - mountpoint: /data
