#
# Cluster and Cloud Computing - Team 20
# 
# Authors: 
#
#  Cenxi Si, Student ID: 1052447
#  Yipei Liu, Student ID: 1067990
#  Jingdan Zhang, Student ID: 1054101
#  Chengyan Dai, Student ID: 1054219
#  Ruimin Sun, Student ID: 1052182
#

---
# Install dependencies on the host
- name: Install pip
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev', 'python3-setuptools', 'python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update && sudo apt-get install python3-dev python3-setuptools python-pip

- name: Update pip
  ansible.builtin.pip:
    name: ['pip', 'openstacksdk']
    state: latest
# pip install --upgrade pip && pip install openstacksdk
