#
# Cluster and Cloud Computing - Team 20
# 
# Authors: 
#
#  Cenxi Si, Student ID: 1052447, China
#  Yipei Liu, Student ID: 1067990, China
#  Jingdan Zhang, Student ID: 1054101, China
#  Chengyan Dai, Student ID: 1054219, Melbourne
#  Ruimin Sun, Student ID: 1052182, China
#

---
# Stop the existing Docker container and remove it if there is any Docker container named couchdb
- name: remove container
  become: yes
  community.docker.docker_container:
    name: couchdb
    state: absent

# Create Docker containers for couchdb
- name: Create Docker containers for couchdb
  become: yes
  docker_container:
    name: couchdb
    image: "ibmcom/couchdb3:{{ couchdb_version }}"
    state: started
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - /data
    env:
      COUCHDB_USER: "{{ user }}"
      COUCHDB_PASSWORD: "{{ password }}"
      COUCHDB_SECRET: "{{ cookie }}"
      ERL_FLAGS: "-setcookie \"{{ cookie }}\" -name \"couchdb@{{ inventory_hostname }}\"" #inventory_hostname应该是当前node
